import { useApp, memberName } from '../../app/AppContext';
import { navigate } from '../../app/router';
import { EmptyState, PageHeader, StatusBadge, formatTime, formatYen } from '../../design-system/components';
import { AlertIcon, ArrowIcon, CheckIcon, RainIcon } from '../../design-system/icons';

export function TodayPage() {
  const { snapshot, loading, can, requestQuickCreate } = useApp();
  const mine = snapshot.todos.filter((todo) => todo.assigneeMembershipId === snapshot.viewer.membershipId && todo.status !== 'done');
  const unsettled = snapshot.expenses.reduce((total, expense) => total + expense.shares.reduce((sum, share) => sum + Math.max(0, share.amountJpy - share.settledJpy), 0), 0);
  const reviewTodo = snapshot.todos.find((todo) => todo.status === 'review');
  const weatherEvent = snapshot.events.find((event) => event.weatherSensitive) ?? snapshot.events[0];
  if (loading) return <div className="page" aria-busy="true" aria-label="今日の情報を読み込んでいます"><PageHeader eyebrow="今日" title={`おはよう、${snapshot.user.displayName}さん`} description="今日の予定とタスクを読み込んでいます。"/><div className="grid two"><div className="skeleton"/><div className="skeleton"/><div className="skeleton"/><div className="skeleton"/></div></div>;
  if (snapshot.events.length + snapshot.todos.length + snapshot.expenses.length === 0) return <div className="page"><PageHeader eyebrow="今日" title={`おはよう、${snapshot.user.displayName}さん`} description="今日の予定やタスクを確認できます。"/><EmptyState title="今日の予定やタスクはありません" action={can('event.create') ? <button className="button primary" onClick={() => requestQuickCreate('event')}>予定を追加</button> : undefined}>共有された予定やタスクが追加されると、時刻順に表示されます。</EmptyState></div>;

  return <div className="page"><PageHeader eyebrow="今日 · 9月30日" title={`おはよう、${snapshot.user.displayName}さん`} description="確認が必要な予定やタスクから順に表示しています。" action={<span className="badge success"><span className="status-dot"/>最終更新 7:29</span>} />
    <div className="stack">
      {(reviewTodo || weatherEvent) && <section className="card accent" aria-labelledby="attention-title"><div className="section-head"><div><p className="eyebrow">01 · 要確認</p><h2 id="attention-title">先に確認すること</h2></div><StatusBadge tone="attention">{Number(Boolean(reviewTodo)) + Number(Boolean(weatherEvent))}件</StatusBadge></div><div className="grid two">{reviewTodo && <div className="callout"><AlertIcon/><div><strong>確認待ちのタスクがあります</strong><p className="muted small">{reviewTodo.title} · 担当：{memberName(snapshot, reviewTodo.assigneeMembershipId)} · 確認する人：{memberName(snapshot, reviewTodo.reviewerMembershipId)}</p></div><a className="button" href={`/tasks/${reviewTodo.id}`} data-link>タスクを確認 <ArrowIcon width="16"/></a></div>}{weatherEvent && <div className="callout info"><RainIcon/><div><strong>{snapshot.context.weather.alert}</strong><p className="muted small">{weatherEvent.title}に影響する可能性があります</p></div><a className="button" href={`/calendar/${weatherEvent.id}`} data-link>予定を開く <ArrowIcon width="16"/></a></div>}</div></section>}

      <section className="card" aria-labelledby="timeline-title"><div className="section-head"><div><p className="eyebrow">02 · 今日の予定</p><h2 id="timeline-title">時刻順に確認</h2></div><a href="/calendar" data-link>予定一覧へ</a></div><ul className="list timeline">{snapshot.events.filter((event) => event.startsAt.startsWith('2026-09-30')).map((event) => <li className="list-row" key={event.id}><time className="time">{formatTime(event.startsAt)}</time><div className="row-main"><strong>{event.title}</strong><span className="meta">{event.location ?? memberName(snapshot, event.ownerMembershipId)}</span></div><button className="button" type="button" aria-label={`${event.title}を開く`} onClick={() => navigate(`/calendar/${event.id}`)}>開く</button></li>)}{snapshot.todos.filter((todo) => todo.dueAt?.startsWith('2026-09-30')).slice(0,1).map((todo) => <li className="list-row" key={todo.id}><time className="time">{formatTime(todo.dueAt)}</time><div className="row-main"><strong>{todo.title}</strong><span className="meta">担当：{memberName(snapshot, todo.assigneeMembershipId)}</span></div><StatusBadge>タスク</StatusBadge></li>)}</ul></section>

      <div className="grid two"><section className="card" aria-labelledby="mine-title"><div className="section-head"><div><p className="eyebrow">03 · 自分の担当</p><h2 id="mine-title">{snapshot.user.displayName}さんのタスク</h2></div><span className="metric">{mine.length}</span></div><ul className="list">{mine.map((todo) => <li className="list-row" key={todo.id}><CheckIcon width="20"/><div className="row-main"><strong>{todo.title}</strong><span className="meta">{formatTime(todo.dueAt)}{todo.reviewerMembershipId ? ` · 確認する人 ${memberName(snapshot, todo.reviewerMembershipId)}` : ''}</span></div><a className="button" href={`/tasks/${todo.id}`} data-link aria-label={`${todo.title}を開く`}>開く</a></li>)}</ul></section>
        {can('expense.read') && <section className="card" aria-labelledby="settle-title"><div className="section-head"><div><p className="eyebrow">04 · 未精算</p><h2 id="settle-title">未精算の合計</h2></div><StatusBadge tone="attention">{snapshot.expenses.filter((expense) => expense.shares.some((share) => share.amountJpy > share.settledJpy)).length}件</StatusBadge></div><p className="metric">{formatYen(unsettled)}</p><p className="muted">記録済みの支出から計算しています。支払う相手と金額を確認できます。</p><a className="button full" href="/budget" data-link>内訳と精算を確認</a></section>}
      </div>

      <section className="card" aria-labelledby="weather-title"><div className="section-head"><div><p className="eyebrow">05 · 天気による影響</p><h2 id="weather-title">雨と予定</h2></div><RainIcon width="30"/></div><div className="grid three"><div><p className="metric">{snapshot.context.weather.precipitationPercent}%</p><p className="meta">降水確率</p></div><div><p className="metric">{snapshot.context.weather.temperatureC}℃</p><p className="meta">予想気温（東京）</p></div><div><strong>予定は自動で変更しません</strong><p className="muted small">天気予報と、影響する可能性がある予定を表示します。</p></div></div></section>
    </div>
  </div>;
}
