import { useRef, useState } from 'react';
import { useApp, memberName } from '../../app/AppContext';
import { detailId, navigate, useCloseTo } from '../../app/router';
import { Dialog, Drawer, EmptyState, PageHeader, StatusBadge, formatDate } from '../../design-system/components';
import { EyeIcon, FileIcon, NoteIcon, ShieldIcon, UploadIcon } from '../../design-system/icons';
import type { Memo } from '../../domain/types';

const tone = (status: string) => status === 'clean' ? 'success' : status === 'rejected' ? 'danger' : status === 'quarantined' ? 'attention' : 'neutral';

export function NotesPage({ path }: { path: string }) {
  const { snapshot, gateway, refresh, announce, can, executeQueueable } = useApp();
  const [query, setQuery] = useState('');
  const [creating, setCreating] = useState(false);
  const [formError, setFormError] = useState('');
  const [editing, setEditing] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [deleted, setDeleted] = useState<Memo | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const input = useRef<HTMLInputElement>(null);
  const activeId = detailId(path, '/notes');
  const active = snapshot.memos.find((memo) => memo.id === activeId);
  const close = useCloseTo('/notes');
  const filtered = snapshot.memos.filter((memo) => `${memo.title} ${memo.body} ${memo.ocrText}`.toLowerCase().includes(query.toLowerCase()));
  const upload = async (file?: File) => {
    if (!active || !file) return;
    const result = await gateway.memos.uploadAttachment(active.id, file);
    if (!result.ok) { announce(result.error.message); return; }
    await refresh(); announce('添付を隔離領域へ送りました。安全確認の完了まで開けません');
  };
  const create = async (form: HTMLFormElement) => {
    if (submitting) return; setFormError(''); setSubmitting(true); const values = new FormData(form);
    const input = { title: String(values.get('title') ?? ''), body: String(values.get('body') ?? ''), tags: String(values.get('tags') ?? '').split(/[,、]/).map((tag) => tag.trim()).filter(Boolean) };
    const outcome = await executeQueueable({ operation: 'memo.create', summary: `メモ「${input.title}」を作成`, payload: { input } }, () => gateway.memos.createMemo(input)); setSubmitting(false);
    if (outcome.status === 'failed') { setFormError(outcome.error.message); return; }
    if (outcome.status === 'queued') { setCreating(false); return; }
    await refresh(); setCreating(false); announce('メモを作成しました'); navigate(`/notes/${outcome.value.id}`);
  };
  const update = async (memo: Memo, form: HTMLFormElement) => { if (submitting) return; setSubmitting(true); setFormError(''); const values = new FormData(form); const input = { title: String(values.get('title') ?? ''), body: String(values.get('body') ?? ''), tags: String(values.get('tags') ?? '').split(/[,、]/).map((tag) => tag.trim()).filter(Boolean) }; const outcome = await executeQueueable({ operation: 'memo.update', summary: `メモ「${memo.title}」を変更`, payload: { id: memo.id, input, expectedVersion: memo.version } }, () => gateway.memos.updateMemo(memo.id, input, memo.version)); setSubmitting(false); if (outcome.status === 'failed') return setFormError(outcome.error.message); if (outcome.status === 'queued') { setEditing(false); return; } await refresh(); setEditing(false); announce('メモを更新しました'); };
  const remove = async () => { if (!active) return; const result = await gateway.memos.deleteMemo(active.id); if (!result.ok) return announce(`${result.error.message} メモの削除は再送待ちへ保存していません。`); setDeleted(active); setDeleting(false); close(); await refresh(); announce(`「${active.title}」を削除しました`); };
  const restore = async () => { if (!deleted) return; const result = await gateway.memos.restoreMemo(deleted.id); if (!result.ok) return announce(result.error.message); setDeleted(null); await refresh(); announce(`「${result.value.title}」を元に戻しました`); };
  const ownOrAdult = active && (['owner','adult'].includes(snapshot.viewer.role) || active.authorMembershipId === snapshot.viewer.membershipId);
  return <div className="page"><PageHeader eyebrow="メモと文字認識" title="家族のメモ" description="紙のお知らせも、共有したい控えも。文字認識の結果は原本と並べて確認できます。" action={can('memo.create') ? <button className="button primary" type="button" onClick={() => setCreating(true)}><NoteIcon width="18"/>メモを作る</button> : undefined}/>{deleted && <div className="callout info" role="status"><NoteIcon/><div><strong>「{deleted.title}」を削除しました</strong><p className="small muted mb-0">7日以内は元に戻せます。</p></div><button className="button" type="button" onClick={() => void restore()}>元に戻す</button></div>}<div className="field" style={{ maxWidth: '32rem', marginBottom: '1.5rem' }}><label htmlFor="note-search">メモ内を検索</label><input id="note-search" className="input" type="search" placeholder="タイトル、本文、文字認識結果" value={query} onChange={(event) => setQuery(event.target.value)}/></div>{filtered.length === 0 ? <EmptyState title="一致するメモはありません">検索語を短くするか、新しいメモを作成してください。</EmptyState> : <div className="grid three">{filtered.map((memo) => <a className="card" href={`/notes/${memo.id}`} data-link key={memo.id} style={{ color: 'var(--ink)', textDecoration: 'none' }}><div className="split"><NoteIcon width="24"/><span className="meta">{formatDate(memo.updatedAt)}</span></div><h2>{memo.title}</h2><p className="muted">{memo.body}</p><div className="split"><span className="meta">{memberName(snapshot,memo.authorMembershipId)} · {memo.tags.join(' / ')}</span>{memo.attachments.length > 0 && <StatusBadge tone={tone(memo.attachments[0].status)}>{memo.attachments.length}添付</StatusBadge>}</div></a>)}</div>}
    {active && <Drawer eyebrow="メモの詳細" title={active.title} onClose={close}><div className="stack"><p>{active.body}</p><div><h3>タグ</h3><div className="people">{active.tags.map((tag) => <span className="person-chip" key={tag}>#{tag}</span>)}</div></div><section className="card flat"><div className="section-head"><h3>添付ファイル</h3>{can('memo.attach') && ownOrAdult && <button className="button" type="button" onClick={() => input.current?.click()}><UploadIcon width="17"/>追加</button>}<input ref={input} className="sr-only" type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={(event) => void upload(event.target.files?.[0])}/></div>{active.attachments.length === 0 ? <p className="muted">添付はありません</p> : <ul className="list">{active.attachments.map((attachment) => <li className="list-row" key={attachment.id}><FileIcon width="23"/><div className="row-main"><strong>{attachment.originalName}</strong><span className="meta">{(attachment.byteSize / 1_000_000).toFixed(1)} MB · {attachment.statusMessage}</span></div><StatusBadge tone={tone(attachment.status)}>{attachment.status === 'clean' ? '検査済み' : attachment.status === 'quarantined' ? '確認中' : attachment.status === 'rejected' ? '受付不可' : '確認中'}</StatusBadge></li>)}</ul>}<div className="callout info mt-1"><ShieldIcon/><div><strong>ファイルは安全確認後に開けます</strong><p className="small muted mb-0">本番ではファイルの種類、内容、サイズ、共有権限をサーバー側でも確認します。この参照画面だけで安全性を保証するものではありません。</p></div></div></section>{active.ocrText && <section><div className="section-head"><h3><EyeIcon width="18"/> 文字認識結果</h3><StatusBadge>原本の確認が必要</StatusBadge></div><div className="card flat"><p>{active.ocrText}</p><p className="small muted mb-0">認識結果には誤りがありえます。重要な日時や金額は原本で確認してください。</p></div></section>}{ownOrAdult && <div className="grid two">{can('memo.update') && <button className="button" type="button" onClick={() => setEditing(true)}>内容を編集</button>}{can('memo.delete') && <button className="button danger" type="button" onClick={() => setDeleting(true)}>メモを削除</button>}</div>}</div></Drawer>}
    {creating && <Dialog title="メモを作る" description="添付は作成後の詳細画面から安全確認へ送れます。" onClose={() => { if (!submitting) { setCreating(false); setFormError(''); } }}><form className="stack" aria-busy={submitting} onSubmit={(event) => { event.preventDefault(); void create(event.currentTarget); }}><label className="field"><span>タイトル</span><input className="input" name="title" required maxLength={120}/></label><label className="field"><span>本文</span><textarea className="textarea" name="body" required maxLength={5000}/></label><label className="field"><span>タグ</span><input className="input" name="tags" placeholder="学校、今週"/><span className="field-help">読点またはカンマで区切ります（最大10件）</span></label>{formError && <p className="field-error" role="alert">{formError}</p>}<div className="dialog-actions"><button className="button" type="button" disabled={submitting} onClick={() => setCreating(false)}>キャンセル</button><button className="button primary" type="submit" disabled={submitting}>{submitting ? '作成中…' : '作成する'}</button></div></form></Dialog>}
    {active && editing && <Dialog title="メモを編集" description="保存前の入力はこの画面に保持されます。" onClose={() => { if (!submitting) setEditing(false); }}><form className="stack" aria-busy={submitting} onSubmit={(event) => { event.preventDefault(); void update(active, event.currentTarget); }}><label className="field"><span>タイトル</span><input className="input" name="title" required maxLength={120} defaultValue={active.title}/></label><label className="field"><span>本文</span><textarea className="textarea" name="body" required maxLength={5000} defaultValue={active.body}/></label><label className="field"><span>タグ</span><input className="input" name="tags" defaultValue={active.tags.join('、')}/></label>{formError && <p className="field-error" role="alert">{formError}</p>}<div className="dialog-actions"><button className="button" type="button" disabled={submitting} onClick={() => setEditing(false)}>キャンセル</button><button className="button primary" type="submit" disabled={submitting}>{submitting ? '保存中…' : '変更を保存'}</button></div></form></Dialog>}
    {active && deleting && <Dialog title="メモを削除しますか" description={`「${active.title}」を共有画面から削除します。`} onClose={() => setDeleting(false)} actions={<><button className="button" type="button" onClick={() => setDeleting(false)}>キャンセル</button><button className="button danger" type="button" onClick={() => void remove()}>削除する</button></>}><p className="muted">添付を含めて非表示になります。削除後7日間は元に戻せます。</p></Dialog>}
  </div>;
}
