import { useApp } from '../../app/AppContext';
import type { Scenario } from '../../domain/types';
import { PageHeader, StatusBadge } from '../../design-system/components';
import { CalendarIcon, CheckIcon, NoteIcon, SparkIcon, YenIcon } from '../../design-system/icons';

const scenarios: Array<[Scenario,string]> = [['normal','通常'],['empty','空'],['loading','読込'],['offline','オフライン'],['conflict','競合'],['expired-invite','期限切れ招待'],['expired-session','セッション切れ'],['quarantined','添付隔離'],['weather','荒天']];
const routes = [['/today','今日',SparkIcon],['/calendar','予定',CalendarIcon],['/tasks','Todo',CheckIcon],['/notes','メモ/OCR',NoteIcon],['/budget','家計・割り勘',YenIcon]] as const;

export function ShowcasePage() {
  const { scenario, setScenario, theme, setTheme } = useApp();
  return <div className="page"><PageHeader eyebrow="Showcase" title="参照実装のショーケース" description="画面、状態、テーマを横断して、実装境界と視覚言語を確認できます。"/><section className="card accent"><div className="section-head"><div><p className="eyebrow">Scenarios</p><h2>異常状態を再現</h2></div><StatusBadge tone={scenario === 'normal' ? 'success' : 'attention'}>{scenario}</StatusBadge></div><div className="segmented" style={{ flexWrap: 'wrap', borderRadius: 'var(--radius-md)' }}>{scenarios.map(([value,label]) => <button key={value} type="button" aria-pressed={scenario === value} onClick={() => setScenario(value)}>{label}</button>)}</div><p className="small muted mt-1">選択すると固定シードの読込状態が切り替わります。オフライン・競合では直近データを残して復旧経路を表示します。</p></section><section className="mt-1"><p className="eyebrow">Screens</p><h2>主要画面</h2><div className="grid three">{routes.map(([href,label,Icon],index) => <a className="card" href={href} data-link key={href} style={{ color: 'var(--ink)', textDecoration: 'none' }}><Icon width="28"/><p className="eyebrow mt-1">0{index+1}</p><h2>{label}</h2><p className="muted small">操作可能なモックデータと詳細URLを含みます。</p></a>)}</div></section><section className="card mt-1"><div className="section-head"><div><p className="eyebrow">Visual language</p><h2>紙、インク、季節色</h2></div><div className="segmented"><button type="button" aria-pressed={theme === 'light'} onClick={() => setTheme('light')}>明</button><button type="button" aria-pressed={theme === 'dusk'} onClick={() => setTheme('dusk')}>夕景</button></div></div><div className="grid three"><div><div style={{ height: '5rem', borderRadius: '1rem', background: 'var(--indigo)' }}/><strong>藍</strong><p className="small muted">情報と信頼</p></div><div><div style={{ height: '5rem', borderRadius: '1rem', background: 'var(--persimmon)' }}/><strong>柿</strong><p className="small muted">注意と季節</p></div><div><div style={{ height: '5rem', borderRadius: '1rem', background: 'var(--moss)' }}/><strong>苔</strong><p className="small muted">落ち着きと完了</p></div></div></section><section className="card mt-1"><p className="eyebrow">Evidence status</p><h2>検証の境界</h2><div className="grid three"><div><StatusBadge tone="success">実装済み</StatusBadge><p className="small mt-1">静的UI、型、モック操作、レスポンシブ、テーマ</p></div><div><StatusBadge tone="attention">契約のみ</StatusBadge><p className="small mt-1">サーバー認証、Cookie、CSRF、添付検疫</p></div><div><StatusBadge>evidence-pending</StatusBadge><p className="small mt-1">実家庭ユーザーによる認知・使いやすさ評価</p></div></div></section></div>;
}
