import { useApp } from '../../app/AppContext';
import type { Scenario } from '../../domain/types';
import { PageHeader, StatusBadge } from '../../design-system/components';
import { CalendarIcon, CheckIcon, NoteIcon, SparkIcon, YenIcon } from '../../design-system/icons';
import { ja } from '../../content/ja';

const scenarios = (Object.keys(ja.scenario) as Scenario[]).map((value) => [value, ja.scenario[value]] as const);
const routes = [['/today','今日',SparkIcon],['/calendar','予定',CalendarIcon],['/tasks','タスク',CheckIcon],['/notes','メモ・文字認識',NoteIcon],['/budget','家計・精算',YenIcon]] as const;

export function ShowcasePage() {
  const { scenario, setScenario, theme, setTheme } = useApp();
  return <div className="page"><PageHeader eyebrow="内部監査" title="画面と状態の確認" description="画面、表示状態、配色を切り替えて、見え方と操作を確認できます。"/><section className="card accent"><div className="section-head"><div><p className="eyebrow">表示状態</p><h2>さまざまな状態を確認</h2></div><StatusBadge tone={scenario === 'normal' ? 'success' : 'attention'}>{ja.scenario[scenario]}</StatusBadge></div><div className="segmented scenario-segmented">{scenarios.map(([value,label]) => <button data-control-id={`showcase.scenario.${value}`} key={value} type="button" aria-pressed={scenario === value} onClick={() => setScenario(value)}>{label}</button>)}</div><p className="small muted mt-1">選ぶと、確認用データの表示状態が切り替わります。接続できない場合や変更が重なった場合は、直前の内容と次にできる操作を表示します。</p></section><section className="mt-1"><p className="eyebrow">画面</p><h2>主な画面</h2><div className="grid three">{routes.map(([href,label,Icon],index) => <a data-control-id={`showcase.route.${href.replace(/^\//, "").replaceAll("/", ".")}`} className="card" href={href} data-link key={href} style={{ color: 'var(--ink)', textDecoration: 'none' }}><Icon width="28"/><p className="eyebrow mt-1">0{index+1}</p><h2>{label}</h2><p className="muted small">確認用データを使って操作できます。項目ごとの画面も開けます。</p></a>)}</div></section><section className="card mt-1"><div className="section-head"><div><p className="eyebrow">配色と質感</p><h2>紙、インク、季節の色</h2></div><div className="segmented"><button data-control-id="showcase.theme.light" type="button" aria-pressed={theme === 'light'} onClick={() => setTheme('light')}>明るい配色</button><button data-control-id="showcase.theme.dusk" type="button" aria-pressed={theme === 'dusk'} onClick={() => setTheme('dusk')}>夕景の配色</button></div></div><div className="grid three"><div><div style={{ height: '5rem', borderRadius: '1rem', background: 'var(--indigo)' }}/><strong>藍</strong><p className="small muted">情報と信頼</p></div><div><div style={{ height: '5rem', borderRadius: '1rem', background: 'var(--persimmon)' }}/><strong>柿</strong><p className="small muted">注意と季節</p></div><div><div style={{ height: '5rem', borderRadius: '1rem', background: 'var(--moss)' }}/><strong>苔</strong><p className="small muted">落ち着きと完了</p></div></div></section><section className="card mt-1"><p className="eyebrow">検証状況</p><h2>確認できている範囲</h2><div className="grid three"><div><StatusBadge tone="success">実装・自動確認済み</StatusBadge><p className="small mt-1">画面、データ形式、確認用操作、画面幅への対応、配色</p></div><div><StatusBadge tone="attention">接続先での対応が必要</StatusBadge><p className="small mt-1">サインインの管理、不正な送信の防止、添付ファイルの安全確認</p></div><div><StatusBadge>利用者による評価待ち</StatusBadge><p className="small mt-1">実際の家庭での分かりやすさと使いやすさ</p></div></div></section></div>;
}
