import { useState } from 'react';
import { useApp, memberName } from '../../app/AppContext';
import { detailId, navigate, useCloseTo } from '../../app/router';
import { Drawer, EmptyState, PageHeader, StatusBadge, formatDate, formatTime } from '../../design-system/components';
import { CalendarIcon, LinkIcon, PeopleIcon, RainIcon } from '../../design-system/icons';

const dates = [28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,1];
const isoFor = (index: number, day: number) => index < 3 ? `2026-09-${day}` : index > 33 ? '2026-11-01' : `2026-10-${String(day).padStart(2,'0')}`;

export function CalendarPage({ path }: { path: string }) {
  const { snapshot } = useApp();
  const [selected, setSelected] = useState('2026-09-30');
  const activeId = detailId(path, '/calendar');
  const active = snapshot.events.find((event) => event.id === activeId);
  const close = useCloseTo('/calendar');
  const eventsFor = (date: string) => snapshot.events.filter((event) => event.startsAt.slice(0,10) === date);
  return <div className="page"><PageHeader eyebrow="Calendar" title="家族の予定" description="一日、一週間、繰り返し。その予定が誰に関係するかまで見渡せます。" action={<button className="button primary" type="button" onClick={() => document.querySelector<HTMLButtonElement>('.quick-create')?.click()}>予定を追加</button>}/>
    {snapshot.events.length === 0 ? <EmptyState title="予定はまだありません">最初の予定を作ると、家族の時間軸が始まります。</EmptyState> : <div className="calendar-layout"><section aria-label="2026年10月のカレンダー"><div className="section-head"><h2>2026年 10月</h2><div className="segmented"><button type="button" aria-pressed="true">月</button><button type="button" aria-pressed="false">週</button><button type="button" aria-pressed="false">一覧</button></div></div><div className="month">{['日','月','火','水','木','金','土'].map((day) => <div className="weekday" key={day}>{day}</div>)}{dates.map((day,index) => { const iso = isoFor(index,day); const events = eventsFor(iso); return <button type="button" className={`day ${index < 3 || index > 33 ? 'outside' : ''}`} key={`${iso}-${index}`} aria-label={`${iso}、予定${events.length}件`} aria-pressed={selected === iso} onClick={() => setSelected(iso)}><span className="date-num">{day}</span>{events.map((event) => <span key={event.id} className="calendar-event">{event.title}</span>)}</button>; })}</div></section><aside className="card flat" aria-labelledby="selected-day"><p className="eyebrow">Selected day</p><h2 id="selected-day">{formatDate(`${selected}T12:00:00+09:00`)}</h2>{eventsFor(selected).length === 0 ? <p className="muted">予定はありません。余白も家族の時間です。</p> : <ul className="list">{eventsFor(selected).map((event) => <li className="list-row" key={event.id}><time className="time">{formatTime(event.startsAt)}</time><div className="row-main"><strong>{event.title}</strong><span className="meta">{event.location ?? '場所未設定'}</span></div><button className="button" type="button" onClick={() => navigate(`/calendar/${event.id}`)}>詳細</button></li>)}</ul>}<hr style={{ border: 0, borderTop: '1px solid var(--line)', margin: '1.5rem 0' }}/><h3>次の祝日</h3><p className="muted">10月12日（月）スポーツの日</p></aside></div>}
    {active && <Drawer eyebrow="Event detail" title={active.title} onClose={close}><div className="stack"><div className="callout info"><CalendarIcon/><div><strong>{formatDate(active.startsAt)} {formatTime(active.startsAt)}〜{formatTime(active.endsAt)}</strong><p className="muted small mb-0">{active.timezone}</p></div></div>{active.weatherSensitive && <div className="callout"><RainIcon/><div><strong>雨の影響候補</strong><p className="small muted mb-0">降水確率80%。自動変更はしません。</p></div></div>}<div className="card flat"><h3><PeopleIcon width="18"/> 関係する人</h3><p>{active.participantMembershipIds.map((id) => memberName(snapshot,id)).join('、')}</p><h3>場所</h3><p>{active.location ?? '未設定'}</p>{active.recurrence && <><h3>繰り返し</h3><p><StatusBadge>毎週</StatusBadge> <code>{active.recurrence.rrule}</code></p><label className="field"><span>編集対象</span><select className="select" defaultValue="this"><option value="this">今回のみ</option><option value="future">今回以降</option><option value="series">系列全体</option></select></label></>}</div>{active.resourceIds?.length && <div><h3>関連リソース</h3><a href="/settings/resources" data-link><LinkIcon width="16"/> 青葉小学校 保護者ページ</a></div>}<div className="grid two"><button className="button" type="button">編集する</button><button className="button danger" type="button">予定を削除</button></div></div></Drawer>}
  </div>;
}
